name: pipeline-commons
version: 0.1.0.0
github: "aleperaltabazas/pipeline-commons"
license: BSD3
author: "Alejandro Peralta Bazas"
maintainer: "aleperaltabazas@gmail.com"
copyright: "2023 Alejandro Peralta Bazas"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/aleperaltabazas/pipeline/pipeline-commons#readme>

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - QuasiQuotes
  - NoImplicitPrelude
  - DeriveGeneric

library:
  source-dirs: src

tests:
  pipeline-commons-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - pipeline-commons
